// <auto-generated />
using BudgetApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BudgetApp.Data.Migrations
{
    [DbContext(typeof(BudgetContext))]
    partial class BudgetContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BudgetApp.Models.BudgetOwner", b =>
                {
                    b.Property<int>("BudgetOwnerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BudgetOwnerName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("BudgetOwnerID");

                    b.ToTable("BudgetOwners");
                });

            modelBuilder.Entity("BudgetApp.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("CategoryName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Bolig"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "Forsikring"
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "Multimedier"
                        },
                        new
                        {
                            CategoryID = 4,
                            CategoryName = "Transport"
                        });
                });

            modelBuilder.Entity("BudgetApp.Models.MonthData", b =>
                {
                    b.Property<int>("MonthDataID")
                        .HasColumnType("int");

                    b.Property<string>("MonthDataString")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.HasKey("MonthDataID");

                    b.ToTable("MonthData");

                    b.HasData(
                        new
                        {
                            MonthDataID = 1,
                            MonthDataString = "Jan"
                        },
                        new
                        {
                            MonthDataID = 2,
                            MonthDataString = "Feb"
                        },
                        new
                        {
                            MonthDataID = 3,
                            MonthDataString = "Mar"
                        },
                        new
                        {
                            MonthDataID = 4,
                            MonthDataString = "Apr"
                        },
                        new
                        {
                            MonthDataID = 5,
                            MonthDataString = "Maj"
                        },
                        new
                        {
                            MonthDataID = 6,
                            MonthDataString = "Jun"
                        },
                        new
                        {
                            MonthDataID = 7,
                            MonthDataString = "Jul"
                        },
                        new
                        {
                            MonthDataID = 8,
                            MonthDataString = "Aug"
                        },
                        new
                        {
                            MonthDataID = 9,
                            MonthDataString = "Sep"
                        },
                        new
                        {
                            MonthDataID = 10,
                            MonthDataString = "Okt"
                        },
                        new
                        {
                            MonthDataID = 11,
                            MonthDataString = "Nov"
                        },
                        new
                        {
                            MonthDataID = 12,
                            MonthDataString = "Dec"
                        });
                });

            modelBuilder.Entity("BudgetApp.Models.SubCategory", b =>
                {
                    b.Property<int>("SubCategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("SubCategoryID");

                    b.ToTable("SubCategories");
                });

            modelBuilder.Entity("BudgetApp.Models.TransactionType", b =>
                {
                    b.Property<int>("TransactionTypeID")
                        .HasColumnType("int");

                    b.Property<string>("TransactionTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TransactionTypeID");

                    b.ToTable("TransactionTypes");

                    b.HasData(
                        new
                        {
                            TransactionTypeID = 1,
                            TransactionTypeName = "Udgifter"
                        },
                        new
                        {
                            TransactionTypeID = 2,
                            TransactionTypeName = "Indtægter"
                        });
                });

            modelBuilder.Entity("BudgetApp.Models.YearData", b =>
                {
                    b.Property<int>("YearDataID")
                        .HasColumnType("int");

                    b.HasKey("YearDataID");

                    b.ToTable("YearData");

                    b.HasData(
                        new
                        {
                            YearDataID = 2001
                        },
                        new
                        {
                            YearDataID = 2002
                        },
                        new
                        {
                            YearDataID = 2003
                        },
                        new
                        {
                            YearDataID = 2004
                        },
                        new
                        {
                            YearDataID = 2005
                        },
                        new
                        {
                            YearDataID = 2006
                        },
                        new
                        {
                            YearDataID = 2007
                        },
                        new
                        {
                            YearDataID = 2008
                        },
                        new
                        {
                            YearDataID = 2010
                        },
                        new
                        {
                            YearDataID = 2011
                        },
                        new
                        {
                            YearDataID = 2012
                        },
                        new
                        {
                            YearDataID = 2013
                        },
                        new
                        {
                            YearDataID = 2014
                        },
                        new
                        {
                            YearDataID = 2015
                        },
                        new
                        {
                            YearDataID = 2016
                        },
                        new
                        {
                            YearDataID = 2017
                        },
                        new
                        {
                            YearDataID = 2018
                        },
                        new
                        {
                            YearDataID = 2019
                        },
                        new
                        {
                            YearDataID = 2020
                        },
                        new
                        {
                            YearDataID = 2021
                        },
                        new
                        {
                            YearDataID = 2022
                        },
                        new
                        {
                            YearDataID = 2023
                        },
                        new
                        {
                            YearDataID = 2024
                        },
                        new
                        {
                            YearDataID = 2025
                        },
                        new
                        {
                            YearDataID = 2026
                        },
                        new
                        {
                            YearDataID = 2027
                        },
                        new
                        {
                            YearDataID = 2028
                        },
                        new
                        {
                            YearDataID = 2029
                        },
                        new
                        {
                            YearDataID = 2030
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
